services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: demo_django
      MYSQL_ROOT_PASSWORD: LusuCard
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    image: alansquid/demo_django
    command: >
      sh -c "
      python /app/src/manage.py migrate &&
      python /app/src/manage.py loaddata todo_seeders.json &&
      python /app/src/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_NAME: demo_django
      DB_USER: root
      DB_PASSWORD: LusuCard
      DB_HOST: db
      DB_PORT: 3306

volumes:
  db_data: 